name: Daily LightHouse Check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: npm install -g @unlighthouse/cli puppeteer netlify-cli

      - name: Generate Config File
        run: |
          cat <<EOF > unlighthouse.config.ts
          export default {
          site: '${{ secrets.SITE }}',
          scanner: {
            maxRoutes: '3000'
          }
          }
          EOF

      - name: Check and build 
        run: unlighthouse-ci --site ${{ secrets.SITE }} --build-static

      - name: Deploy
        run: netlify deploy --dir=.unlighthouse --prod --message="New Release Deploy from GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
