name: Daily LightHouse Check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: npm install -g @unlighthouse/cli puppeteer netlify-cli

      - name: Generate Config File
        run: |
          cat <<EOF > unlighthouse.config.ts
          export default {
          site: '${{ secrets.SITE }}',
          scanner: {
            maxRoutes: '3000',
            sitemap: [
          'post-sitemap.xml',
          'page-sitemap.xml'
          ],
          exclude: [
          '/en/*',
          '/ko/*',
          '/ja/*',
          '/zh-hans/*',
          '/khuyen-mai-*'
          ]
          }
          }
          EOF

      - name: Check Config File
        run: ls -d "$PWD/unlighthouse.config.ts"

      - name: Check and build 
        run: unlighthouse-ci --config-file ./unlighthouse.config.ts --enable-i18n-pages --build-static

      - name: Deploy
        run: netlify deploy --dir=.unlighthouse --prod --message="Daily Performance Report"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
