name: Daily Check (Mobile)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'
      
      - name: Install Dependencies
        run: |
          npm install @unlighthouse/cli puppeteer netlify-cli

      - name: Generate Config File
        run: |
          cat <<EOF > unlighthouse.config.ts
          export default {
            site: '${{ secrets.SITE }}',
            scanner: {
              device: 'mobile',
              throttle: false,
              dynamicSampling: false,
              maxConcurrency: 2,
              samples: 3,
              sitemap: false,
              robotsTxt: false,
              crawler: false,
            }
          }
          EOF

      - name: Check and Build
        run: npx unlighthouse-ci --urls /,/alibaba-cloud-anti-ddos,/alibaba-cloud-cdn,/alibaba-cloud-ecs-elastic-compute-service,/alibaba-cloud-elasticsearch,/alibaba-cloud-gia-re,/apsaradb-for-redis,/bang-gia-license,/bang-gia-ten-mien,/bieu-mau-ho-so-dang-ky,/category/tuyen-dung,/chinh-sach-bao-hanh-dich-vu-thiet-ke-website,/chinh-sach-dung-thu-vps,/chuyen-nhuong-ten-mien,/cloudbox,/cloud-vps-singapore,/cong-tac-vien,/container-service-for-kubernetes,/dang-ky-ten-mien,/dang-nhap,/database-hosting,/dcdn,/dia-chi-ip-cambodia,/dia-chi-ip-han-quoc,/dia-chi-ip-my,/dia-chi-ip-singapore,/dia-chi-ip-thai-lan,/dia-chi-ip-viet-nam,/dich-vu-cdn-chuyen-nghiep,/dich-vu-dai-ly,/dich-vu-dynamic-dns,/dich-vu-object-storage,/dich-vu-pro-dns,/dich-vu-registry-lock,/dich-vu-sao-luu-du-lieu,/dich-vu-waf,/dich-vu-whois-protection,/dnssec,/edge-node-service,/elastic-ip-address,/email-hosting-chuyen-nghiep,/email-marketing-hieu-qua,/email-relay,/email-server-doanh-nghiep,/geotrust-ssl,/gioi-thieu,/google-workspace,/google-workspace-business-plus,/google-workspace-enterprise,/hosting-cao-cap,/hosting-dai-ly,/hosting-doanh-nghiep,/hosting-gia-re,/hosting-mien-phi,/hosting-n8n,/hosting-singapore,/ho-tro,/huong-ung-ngay-chuyen-doi-so-quoc-gia-nam-2024,/hybrid-email,/lien-he,/may-chu-ao-cambodia,/may-chu-ao-thai-lan,/may-chu-ao-vps-indonesia,/may-chu-rieng-cambodia,/may-chu-rieng-canada,/may-chu-rieng-han-quoc,/may-chu-rieng-indonesia,/may-chu-rieng-singapore,/may-chu-rieng-tai-my,/may-chu-rieng-thai-lan,/microsoft-365,/mua-ssl-gia-re,/object-storage-service,/private-cloud-gia-re,/quy-dinh-su-dung-ten-mien-viet-nam,/sectigo-ssl,/sectigo-ssl-ip,/seo-hosting,/server/may-chu-mmo,/server/quan-tri-may-chu,/server/server-an-do,/server/thue-cho-dat-may-chu-uy-tin,/server/thue-cloud-server,/server/thue-may-chu-rieng,/server-game,/server-lao,/server-load-balancer,/server-malaysia,/server-philippines,/simple-application-server,/snapshot-file-backup,/ten-mien-vn,/thanh-toan,/thoa-thuan-su-dung-ten-mien-quoc-te,/thue-vps-gia-re,/tong-quan-dich-vu-vps,/trach-nhiem-quan-ly-ten-mien,/vps-cao-cap,/vps-duc,/vps-forex,/vps-forex-indonesia,/vps-gpu,/vps-lao,/vps-malaysia,/vps-minecraft,/vps-mmo,/vps-n8n,/vps-nvme,/vps-windows,/web-application-firewall,/windows-hosting,/wordpress-hosting --build-static --reporter csv

      - name: Upload CSV
        run: |
          curl -X POST \
            -H "Content-Type: text/csv" \
            --data-binary "@.unlighthouse/ci-result.csv" \
            ${{ secrets.HOOK_M }}

      - name: Deploy
        run: npx netlify deploy --dir=.unlighthouse --prod --message="Daily Performance Report (Mobile)"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_MOBILE_ID }}
