name: Daily Check (Mobile)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * 0'

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: npm install -g @unlighthouse/cli puppeteer netlify-cli

      - name: Generate Config File
        run: |
          cat <<EOF > unlighthouse.config.ts
          export default {
          site: '${{ secrets.SITE }}',
          scanner: {
            device: 'mobile',
            dynamicSampling: false,
            robotsTxt: false,
            maxRoutes: '3000',
            sitemap: [
            '/post-sitemap.xml',
            '/page-sitemap.xml'
          ],
          exclude: [
          '/en/*',
          '/ko/*',
          '/ja/*',
          '/zh-hans/*',
          '/khuyen-mai-*'
          ]
          }
          }
          EOF

      - name: Check and build 
        run: unlighthouse-ci --config-file ./unlighthouse.config.ts --disable-i18n-pages --build-static

      - name: Deploy
        run: netlify deploy --dir=.unlighthouse --prod --message="Daily Performance Report (Mobile)"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_MOBILE_ID }}
