name: Daily Check (Mobile)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * 0'

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Install Dependencies
        run: |
          - name: Setup Node.js
            uses: actions/setup-node@v3
            with:
              node-version: '22'
              cache: 'npm'
          
          - name: Install Dependencies
            run: |
              npm install @unlighthouse/cli puppeteer netlify-cli

      - name: Generate Config File
        run: |
          cat <<EOF > unlighthouse.config.ts
          export default {
            site: '${{ secrets.SITE }}',
            scanner: {
              device: 'mobile',
              throttle: false,
              dynamicSampling: false,
              maxConcurrency: 2,
              samples: 3,
              sitemap: false,
              robotsTxt: false,
              crawler: false,
            }
          }
          EOF

      - name: Check and Build
        run: npx unlighthouse-ci --config-file ./unlighthouse.config.ts / --build-static --reporter csv

      - name: Upload CSV
        run: |
          curl -X POST \
            -H "Content-Type: text/csv" \
            --data-binary "@.unlighthouse/ci-result.csv" \
            ${{ secrets.HOOK }}

      - name: Deploy
        run: npx netlify deploy --dir=.unlighthouse --prod --message="Daily Performance Report (Mobile)"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_MOBILE_ID }}
